---
- name: Upgrade server
  yum:
    name: '*'
    state: latest

- name: Add repositories
  yum:
    name: epel-release
    state: latest

- name: Install pip
  yum:
    name: python-pip
    state: latest
