---
- name: Make sure destination dir exists
  file:
    path: "/prestashop"
    state: directory

- name: Copy docker-compose.yaml
  copy:
    src: '{{role_path}}/files/docker-compose.yaml'
    dest: '/prestashop/docker-compose.yaml'
    
- name: Run docker-compose
  docker_compose:
    project_src: '/prestashop'
